default_stages: [ commit ]

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        types: [ python ]
        language: system

      - id: isort
        name: isort
        entry: poetry run isort
        types: [ python ]
        language: system

      - id: flake8
        name: flake8
        entry: poetry run flake8
        types: [ python ]
        language: system

#      - id: mypy
#        name: mypy
#        entry: poetry run mypy main.py
#        language: system
#        pass_filenames: false
